# Generated by Django 2.2.3 on 2019-07-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
